apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-k8s.fullname" . }}
  labels:
    {{- include "nginx-k8s.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-k8s.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.exporter.enabled }}
        - name: nginx-exporter
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          args:
            - "-nginx.scrape-uri=http://localhost/metrics"
          ports:
            - name: metrics
              containerPort: {{ .Values.exporter.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.exporter.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "nginx-k8s.fullname" . }}
