# Number of NGINX pods to run.
replicaCount: 1
image:
  repository: nginx
  tag: "9b3dfd821b5deff9d5d614640188a34d6cc74809"
  pullPolicy: IfNotPresent
exporter:
  enabled: true
  image:
    repository: nginx/nginx-prometheus-exporter
    tag: "0.11.0"
    pullPolicy: IfNotPresent
  port: 9113
  resources:
    requests:
      cpu: "0.3"
      memory: 128Mi
    limits:
      cpu: "0.5"
      memory: 128Mi
service:
  type: ClusterIP
  port: 9113
# These annotations allow Prometheus installations using pod discovery to
# scrape the exporter directly.
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9113"
resources: {}
nginxConfig: |
  server {
    listen 80;
    location / {
      root /usr/share/nginx/html;
      index index.html index.htm;
    }
    location /metrics {
      stub_status on;
      access_log off;
    }
  }
