name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Lint and render Helm chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4

      - name: Lint chart
        run: helm lint helm/nginx-k8s

      - name: Render chart
        run: helm template nginx helm/nginx-k8s
